name: Build and Push Docker Image

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    name: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
            context: .
            push: true
            tags: noussydjimi/gaming-app:latest
            cache-from: type=registry,ref=noussydjimi/gaming-app:buildcache
            cache-to: type=registry,ref=noussydjimi/gaming-app:buildcache,mode=max
            
  scan:
    name: Scan
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.28.0
        continue-on-error: true
        with:
            image-ref: 'noussydjimi/gaming-app:latest'
            format: 'table'
            exit-code: '1'
            ignore-unfixed: true
            vuln-type: 'os,library'
            severity: 'CRITICAL,HIGH'

  deploy:
    name: deploy on kubernetes
    runs-on: ubuntu-latest
    needs: scan
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: "v3.10.0"

      - name: Verify Helm
        run: helm version

      - name: Lint and template chart
        run: |
          helm lint ./gaming-app --kubeconfig ./kubeconfig
          helm template ./gaming-app --kubeconfig ./kubeconfig

      - name: Install Helm chart
        run: helm upgrade --install gaming-app ./gaming-app --kubeconfig ./kubeconfig

      # - name: Uninstall Helm chart
      #   run: helm delete gaming-app --kubeconfig ./kubeconfig

